"""empty message

Revision ID: 118db60c1b00
Revises: 3f08f292a279
Create Date: 2022-06-18 11:56:50.373847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118db60c1b00'
down_revision = '3f08f292a279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_diary', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer_diary', 'type')
    # ### end Alembic commands ###
