"""empty message

Revision ID: 154359728dd1
Revises: 84c6aa81ae58
Create Date: 2022-06-17 09:24:37.139175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154359728dd1'
down_revision = '84c6aa81ae58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.String(length=200), nullable=False),
    sa.Column('answer_content', sa.TEXT(), nullable=False),
    sa.Column('likes_number', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['user_function.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answer')
    # ### end Alembic commands ###
