"""empty message

Revision ID: 21ba0b78797d
Revises: 154359728dd1
Create Date: 2022-06-17 17:51:32.764878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ba0b78797d'
down_revision = '154359728dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_diary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diary_id', sa.String(length=200), nullable=False),
    sa.Column('function_title', sa.String(length=200), nullable=True),
    sa.Column('function_content', sa.TEXT(), nullable=False),
    sa.Column('Photo', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developer_diary')
    # ### end Alembic commands ###
