"""empty message

Revision ID: 22a37febe690
Revises: 5e6b50890fb6
Create Date: 2022-07-01 15:30:53.906716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a37febe690'
down_revision = '5e6b50890fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('portrait', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'portrait')
    # ### end Alembic commands ###
