"""empty message

Revision ID: 260b05fa5000
Revises: d6de78ff80bb
Create Date: 2022-06-11 00:05:26.555493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '260b05fa5000'
down_revision = 'd6de78ff80bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_captcha', 'email_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               nullable=False)
    op.create_unique_constraint(None, 'email_captcha', ['email_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_captcha', type_='unique')
    op.alter_column('email_captcha', 'email_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               nullable=True)
    # ### end Alembic commands ###
