"""empty message

Revision ID: 3f08f292a279
Revises: e6989f8e7f95
Create Date: 2022-06-18 11:13:28.318586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f08f292a279'
down_revision = 'e6989f8e7f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_answer', 'content_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('content_type', table_name='user_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('content_type', 'user_answer', ['content_type'], unique=False)
    op.alter_column('user_answer', 'content_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
