"""empty message

Revision ID: 815e7b176de0
Revises: f5cffe51d79d
Create Date: 2022-07-05 11:07:05.420504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815e7b176de0'
down_revision = 'f5cffe51d79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('character', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'character')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
