"""empty message

Revision ID: 9c70616b9273
Revises: ad6847ffd2a7
Create Date: 2022-06-11 10:44:24.550213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c70616b9273'
down_revision = 'ad6847ffd2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'user_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
