"""empty message

Revision ID: d6de78ff80bb
Revises: af0fb0629428
Create Date: 2022-06-10 23:55:09.584512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6de78ff80bb'
down_revision = 'af0fb0629428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_captcha', 'email_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'email_captcha', ['email_id'])
    op.drop_column('email_captcha', 'update_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captcha', sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'email_captcha', type_='unique')
    op.alter_column('email_captcha', 'email_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
