"""empty message

Revision ID: f4728125b038
Revises: 21ba0b78797d
Create Date: 2022-06-17 18:02:29.650944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4728125b038'
down_revision = '21ba0b78797d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_diary', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('developer_diary', sa.Column('content', sa.TEXT(), nullable=False))
    op.drop_column('developer_diary', 'function_title')
    op.drop_column('developer_diary', 'function_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_diary', sa.Column('function_content', mysql.TEXT(), nullable=False))
    op.add_column('developer_diary', sa.Column('function_title', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('developer_diary', 'content')
    op.drop_column('developer_diary', 'title')
    # ### end Alembic commands ###
