"""empty message

Revision ID: f9446c9652c6
Revises: c865de72a41c
Create Date: 2022-06-18 09:31:31.703468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9446c9652c6'
down_revision = 'c865de72a41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'root_diary', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'root_diary', type_='unique')
    # ### end Alembic commands ###
